---
title: "Plots with 3 anchors"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have the latest version of rmarkdown and bookdown
#devtools::install_github("rstudio/rmarkdown")
#devtools::install_github("rstudio/bookdown")
library(ggplot2)
library(gravitas)
library(gracsr)
library(ggdendro)
library(dplyr)
library(readr)
library(visdat)
library(ggplot2)
library(tidyverse)
library(naniar)
library(here)
library(tsibble)
library(knitr)
library(patchwork)
library(GGally)
library(distributional)
library(viridis)
```


```{r mytheme}
theme_characterisation <- function() {
  
  theme_bw() + # seeting theme
    theme(strip.text = element_text(size = 9,
                                    margin = margin(b = 0, t = 0))) + # narrow facet space
   theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + # no axis ticks 
  theme(panel.spacing =unit(0, "lines")) +  # to ensure no gap between facets
    theme(axis.text.x = element_text(angle=90, hjust=1, size = 9)) + # rotate the x-axis text
    theme(legend.position = "bottom")+
  theme(plot.margin = margin(0, 0, 0, 0, "cm")) +
  theme(axis.text.x = element_text(size=5))
}
```

_Set number of anchors_
```{r anchor}
kopt <- 3 # number of clusters
```

_Load the customers you want to cluster_
```{r}
quantile_prob_graph <- c(0.25, 0.5, 0.75)

data_pick_one <- c(8618759, 8291696, 10357256, 8290374) %>% as_tibble %>% set_names("customer_id")
data_pick_two <- c(9044864, 8642053, 10534367, 9021526,11162275) %>% as_tibble %>% set_names("customer_id")
data_pick_three <- c(8221762, 8273636, 10359424, 8232822)%>% as_tibble %>% set_names("customer_id")

```

```{r assemble}
data_pick_cust <- bind_rows(
data_pick_one, data_pick_two, data_pick_three,
.id = "design") %>% 
  mutate(customer_id = as.character(customer_id))

```

_Load raw data for these customers and scale it according to robust method_

```{r}
data_pick <- read_rds(here::here("data/elec_nogap_2013_clean_356cust.rds")) %>%
  mutate(customer_id = as.character(customer_id)) %>% 
  filter(customer_id %in% data_pick_cust$customer_id) %>% 
  gracsr::scale_gran( method = "robust",
                      response = "general_supply_kwh")
```


```{r clustering}

hod <- data_pick %>% 
  dist_gran(gran1 = "hour_day", response = "general_supply_kwh") 

moy <- data_pick %>% 
  dist_gran(gran1 = "month_year", response = "general_supply_kwh")

wkndwday <- data_pick %>% 
  dist_gran(gran1 = "wknd_wday", response = "general_supply_kwh")

distance <- wkndwday/2 + moy/12 + hod/24

f = as.dist(distance)

cluster_result <- f %>% clust_gran(kopt = kopt) %>% 
  rename("customer_id" = "id")
```


```{r hod-data}
data_hod <- quantile_gran(data_pick,
                                  "hour_day",
                                  quantile_prob_val = quantile_prob_graph) %>% 
  pivot_wider(names_from = quantiles,
              values_from = quantiles_values) %>% 
  left_join(data_pick_cust, by = c("customer_id")) %>% 
  left_join(cluster_result, by = c("customer_id"))
  
#data_heatmap_hod$customer_id = factor(data_heatmap_hod$customer_id, levels = data_pick_cust$value)
data_hod$category <- factor(data_hod$category, levels = 0:23)

# lev <- data_hod %>% distinct(customer_id, design) %>% arrange(design) %>% pull(customer_id)
```


```{r hod-ind-design}

# data_hod$customer_id <- factor(data_hod$customer_id, levels = lev)

hod_ind_design <- data_hod %>% 
  left_join(cluster_result,by = c("customer_id", "group")) %>% 
  ggplot(aes(x = category)) + 
  geom_ribbon(aes(ymin = `25%`, 
                  ymax = `75%`,
                  group=customer_id, 
                  fill = design),
              alpha = 0.5) +
  geom_line(aes(y = `50%`,
                group=customer_id,
                color = design), 
            size = 1) +
  facet_wrap(design~customer_id, 
             scales = "free_y",
             nrow = kopt) + theme_characterisation()+
  xlab("hour-of-day") +
  scale_fill_viridis_d()+
  scale_color_viridis_d()+
  scale_x_discrete(breaks = seq(0, 23, 3))
```


```{r hod-ind-group}
hod_ind_group <- data_hod %>% 
  left_join(cluster_result) %>% 
  ggplot(aes(x = category)) + 
  geom_ribbon(aes(ymin = `25%`, 
                  ymax = `75%`,
                  group=customer_id, fill = as.factor(group)),
              alpha = 0.5) +
  geom_line(aes(y = `50%`,
                group=customer_id, color = as.factor(group)), size = 1) +
  facet_wrap(design~customer_id, 
             scales = "free_y",
              nrow = kopt) + theme_characterisation()+
  scale_fill_manual(values = c("#E69F00", "#009E73","#0072B2", "#D55E00", "grey"))+
  scale_color_manual(values = c("#E69F00", "#009E73","#0072B2", "#D55E00", "grey")) +    xlab("hour-of-day")  +
  scale_x_discrete(breaks = seq(0, 23, 3))
# + scale_y_continuous(breaks = NULL) 
# 
# 
hod_ind_design + hod_ind_group
```



```{r data-heatmap-moy-design}

data_moy <- quantile_gran(data_pick,
                                  "month_year", 
                                  quantile_prob_val = quantile_prob_graph) %>% 
  pivot_wider(names_from = quantiles, 
              values_from = quantiles_values) %>% 
  left_join(data_pick_cust, by = c("customer_id"))
  
data_moy$category <- factor(data_moy$category, levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))

moy_ind_design <- data_moy %>% 
  left_join(cluster_result, by = c("customer_id")) %>% 
  ggplot(aes(x = category)) + 
  geom_ribbon(aes(ymin = `25%`, 
                  ymax = `75%`, 
                  group=customer_id, fill = as.factor(design)), alpha = 0.5) +
  geom_line(aes(y = `50%`, group=customer_id, color = as.factor(design)), size = 1) +
  facet_wrap(design~customer_id, 
             scales = "free_y", 
             nrow = kopt) +
    ylab("demand (in Kwh)") +
    xlab("month-of-year")  +
  theme_characterisation() +
  scale_fill_viridis_d(direction = 1)+
  scale_color_viridis_d(direction = 1)
```


```{r data-heatmap-moy-group-ind}

moy_ind_group <- data_moy %>% 
  left_join(cluster_result, by = c("customer_id")) %>% 
  ggplot(aes(x = category)) + 
  geom_ribbon(aes(ymin = `25%`, 
                  ymax = `75%`, 
                  group=customer_id, fill = as.factor(group)), alpha = 0.5) +
  geom_line(aes(y = `50%`, group=customer_id, color = as.factor(group)), size = 1) +
  facet_wrap(design~customer_id, 
             scales = "free_y", 
             nrow = kopt) +
    ylab("demand (in Kwh)") +
    xlab("month-of-year")  +
  theme_characterisation() +
  scale_fill_manual(values = c("#E69F00", "#009E73","#0072B2", "#D55E00", "grey"))+
  scale_color_manual(values = c("#E69F00", "#009E73","#0072B2", "#D55E00", "grey"))

moy_ind_design + moy_ind_group

```  

```{r data-heatmap-wkndwday-group}

data_wkndwday <- data_pick  %>%
  left_join(cluster_result)%>% create_gran("wknd_wday")  %>% 
  left_join(data_pick_cust, by = c("customer_id"))

ylim1 = boxplot.stats(data_wkndwday$general_supply_kwh)$stats[c(1, 5)]

wkndwday_ind_design <- data_wkndwday%>% 
  ggplot(aes(x=wknd_wday, y = general_supply_kwh)) +
  lvplot::geom_lv(aes(fill = as.factor(design), 
                      color = as.factor(design)), k=5, alpha = 0.5) +
  #geom_boxplot(aes(fill = as.factor(group), color = as.factor(group)),alpha = 0.5)+
  #geom_boxplot(outlier.shape = NA) + 
  coord_cartesian(ylim = ylim1*1.05)+
  facet_wrap(~customer_id, 
             scales = "free_y", 
             labeller = "label_value",
             nrow = kopt)  +
  theme_characterisation() +
  scale_fill_viridis_d(direction = 1)+
  scale_color_viridis_d(direction = 1)
  

```


```{r}
wkndwday_ind_group <- data_wkndwday%>% 
  ggplot(aes(x=wknd_wday, y = general_supply_kwh)) +
  lvplot::geom_lv(aes(fill = as.factor(group), 
                      color = as.factor(group)), k=5, alpha = 0.5) +
  #geom_boxplot(aes(fill = as.factor(group), color = as.factor(group)),alpha = 0.5)+
  #geom_boxplot(outlier.shape = NA) + 
  coord_cartesian(ylim = ylim1*1.05)+
  facet_wrap(~customer_id, 
             scales = "free_y", 
             labeller = "label_value",
             nrow = kopt)  +
  theme_characterisation() +
  scale_fill_manual(values = c("#E69F00", "#009E73","#0072B2", "#D55E00", "grey"))+
  scale_color_manual(values = c("#E69F00", "#009E73","#0072B2", "#D55E00", "grey"))


wkndwday_ind_design + wkndwday_ind_group
```

