---
title: "Algorithm using wpd values for clustering 100 households"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,echo=FALSE, message=FALSE, warning = FALSE)
```

```{r load-lib}
library(knitr)
library(tidyverse)
library(lubridate)
library(lvplot)
#library(ggridges)
library(tsibble)
library(gravitas)
library(ggpubr)
library(readr)
library(kableExtra)
library(distributional)
library(ggplot2)
library(sugrrants)
library(here)
library(ggplot2)
library(patchwork)
library(scales)
library(GGally)
library(viridis)
```


```{r allplot, message=FALSE, warning=FALSE, echo = FALSE}

##----harmony-all
elec_harmony_all <-read_rds("../../../data/elec_harmony-100-nogap-onegran.rds")

select_split <- str_split(elec_harmony_all$select_harmony, " ", simplify = TRUE)[,2]

elec_sig_split <- elec_harmony_all %>%
  mutate(facet_variable = case_when(
    facet_variable == "hour_day" ~ "hod" ,
    facet_variable == "day_month" ~ "dom" ,
    facet_variable == "day_week" ~ "dow" ,
    facet_variable == "week_month" ~ "wom" ,
    facet_variable == "wknd_wday" ~ "wdwnd"
  )) %>% 
  mutate(x_variable = case_when(
    x_variable == "hour_day" ~ "hod" ,
    x_variable == "day_month" ~ "dom" ,
    x_variable == "day_week" ~ "dow" ,
    x_variable == "week_month" ~ "wom" ,
    x_variable == "wknd_wday" ~ "wdwnd"
  )) %>% 
  bind_cols(select_split = select_split) %>% 
  mutate(significant = case_when(
    select_split == "***" ~ "highest",
    select_split == "**" ~ "high",
    select_split == "*" ~ "medium",
    select_split == "" ~ "low"
  )) %>%mutate(comb = x_variable) 

# %>% 
#   mutate(rank = case_when(
#     select_split == "***" ~ paste(rank, "***", sep = " "),
#     select_split == "**" ~  paste(rank, "**", sep = " "),
#     select_split == "*" ~  paste(rank, "*", sep = " "),
#     select_split == "" ~  paste(rank, "", sep = " ")
#   ))
  
elec_sig_split$significant <- 
  factor(elec_sig_split$significant, levels = c("highest", "high", "medium", "low")) 
  

data_comb_filter = elec_sig_split %>% 
mutate(low_proxy = if_else(significant=="low", 0, 1))%>% 
select(comb, customer_id, low_proxy) %>% 
pivot_wider(names_from = customer_id, values_from = low_proxy) %>% 
mutate(score = rowMeans(across(-1))) %>% 
filter(score !=0)


data_sig_filter = elec_sig_split %>% 
filter(comb %in% data_comb_filter$comb)

data_clust = data_sig_filter %>% 
select(comb, customer_id, wpd) %>% 
pivot_wider(names_from = comb, values_from = wpd) 

hc = stats::hclust(dist(data_clust[-1], method = "manhattan"),method="complete")
#plot(hc)
plot(hc, cex = 0.6)
rect.hclust(hc, k = 8, border = 2:10)


library(fpc)
koptimal = fpc::nselectboot(dist(data_clust[-1], method = "manhattan"),
                        B = 50,
                        method = "complete",
                        clustermethod = disthclustCBI, 
                        classification = "averagedist",
                        krange = 2:8)

koptimal = koptimal$kopt

groups <- cutree(hc, k=8) %>% 
  as_tibble() %>% 
mutate(customer_id = data_clust$customer_id)

##----cluster-characterization

data = data_clust %>% 
left_join(groups)%>% 
             rename ("group" = "value") %>% 
             ungroup() %>% 
             select(group, customer_id, everything()) %>% 
             pivot_longer(-c(1,2), names_to = "comb", values_to = "wpd")

data_pcp <- data %>% pivot_wider(
              names_from = comb, 
              values_from = wpd) %>% 
  mutate(group = as.character(group)) 
```


```{r}
# ggpairs_nocolor <- ggpairs(data_pcp, columns = 3:7)
# ggpairs_nocolor

groupge2 <- data %>% 
  group_by(group) %>% 
  summarise(n = length(unique(customer_id))) %>% 
  filter(n>2)


data_pcp_ge2 <- data_pcp %>% filter(group %in% groupge2$group)

# ggpairs_nocolor <- ggpairs(data_pcp_ge2, columns = 3:7)


ggpairs_nocolor <- ggscatmat(data_pcp_ge2, columns=3:6) +
  scale_colour_brewer(palette="Set2") + theme(legend.position = "bottom")

ggpairs_color <- ggscatmat(data_pcp_ge2, columns=3:6, color = "group") +
  scale_colour_brewer(palette="Set2") + theme(legend.position = "bottom")

ggpairs_nocolor
```

```{r}
ggpairs_color
```

```{r}
# 
# data_order <- data %>% 
#   group_by(comb) %>% 
#   summarise(m = mean(wpd)) %>% 
#   arrange(desc(m))
#   
# data_median = data %>% 
#   group_by(group, comb) %>% 
#   summarize(wpd_med = median(wpd))
# 
# data_pcp <- data_median %>% 
# mutate(group = as.character(group)) %>% 
#   left_join(data_order) %>% 
#   arrange(desc(m)) %>% 
#   pivot_wider(-4, 
#               names_from = comb, 
#               values_from = wpd_med) 
             
data_pcp <- data_pcp %>% ungroup()%>% filter(group %in% groupge2$group)
parcoord <- GGally::ggparcoord(data_pcp ,
                   columns = 3:ncol(data_pcp),
                   groupColumn = "group",
                   showPoints = TRUE, 
                   title = "(c)",
                   alphaLines = 0.3,
                   order = "allClass",
                   scale = "globalminmax"
) + ggplot2::theme_bw() +
  scale_color_brewer(palette = "Dark2") + 
  ggplot2::theme(
    plot.title = ggplot2::element_text(size=10)
  )+
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 10)) +
  theme(legend.position = "bottom") +
  xlab("") +
  ylab("wpd") 
# 
# ggparcoord(data_pcp, scale = "globalminmax", columns=3:ncol(data_pcp),groupColumn = "group", alphaLines = 0.8) + geom_boxplot(aes_string(group = "variable"), width = 0.1, alpha = 0.1,
#                  outlier.color = NA) +  scale_color_brewer(palette = "Dark2") 
#+
 # geom_point(data = data, aes(x=comb, y = wpd)) 

##----read-orig-data

elec <- read_rds("../data/elec_nogap_2013_100.rds") %>% 
  left_join(groups)%>% 
             rename ("group" = "value")



# plot(hc, cex = 0.6)
# rect.hclust(hc, k = 4, border = 2:7)

#elec_zoom
parcoord


elec_scaled <- elec %>%
    group_by(customer_id) %>%
    #dplyr::mutate(general_supply_kwh = scale(general_supply_kwh)) %>%
    ungroup()

  
sm_hod_dow <- elec_scaled %>% 
gravitas::create_gran("hour_day") 

sm_hod_list <- sm_hod_dow %>% 
  as_tibble() %>% 
  arrange(group, hour_day) %>% 
  mutate(category = hour_day) %>% 
   select(group, category, general_supply_kwh) %>% 
  pivot_wider(names_from = category,
              values_from = general_supply_kwh)
 

elec %>% as_tibble() %>% group_by(group) %>% summarise(n = length(unique(customer_id)))
```

```{r}
quantile_prob_val = c(0.25, 0.5, 0.75)

sm_hod <- gravitas::create_gran(sm, "hour_day") %>% 
  mutate(customer_id = as.integer(customer_id))

sm_hod_list <- sm_hod %>% 
  as_tibble() %>% 
  select(customer_id, hour_day, general_supply_kwh) %>% 
  pivot_wider(names_from = hour_day,
              values_from = general_supply_kwh)



groups_ref <- groups %>% as_tibble %>% 
              mutate(customer_serial_id = sm_hod_list$customer_id) %>% 
             rename ("group" = "value")

sm_hod_list_cat <-  sm_hod_list %>% left_join(groups_ref, by = c("customer_id" = "customer_serial_id")) %>% select(group, everything())
  
ncol_sm <- seq_len(ncol(sm_hod_list_cat[-c(1, 2)]))
nrow_sm <- unique(sm_hod_list_cat$group)


sm_hod_quantiles_cat <- map(nrow_sm, function(x){
  map(ncol_sm, function(y){
   cell <- sm_hod_list_cat%>% 
     dplyr::filter(group == x) %>% 
     select(-c(1, 2)) %>% 
     extract(y) %>% 
     unlist()
   quantile(cell, prob = quantile_prob_val)
})  %>% bind_rows(.id = "categories_serial_id")
}) %>% bind_rows(.id = "group_id") %>% 
  mutate(group_id = as.integer(group_id),
         categories_serial_id = as.integer(categories_serial_id))

categories_ref_cat <- names(sm_hod_list_cat)[-c(1, 2)] %>% as_tibble() %>% 
  mutate(categories_serial_id = row_number())


data_heatmap <- sm_hod_quantiles_cat %>% 
  pivot_longer(-c(1, 2), names_to = "quantile_prob", values_to = "quantile_val") %>% 
  left_join(categories_ref_cat) %>% 
  rename("category" = "value") %>% 
  select(-categories_serial_id) %>% 
  mutate(category = as.numeric(category))
```



```{r cluster-characterization}
data_heatmap %>% 
  pivot_wider( names_from = quantile_prob, 
               values_from = quantile_val) %>% 
  ggplot(aes(x = category)) +  geom_ribbon(aes(ymin = `25%`, 
                  ymax = `75%`), fill = "lightblue") +
  geom_line(aes(y = `50%`)) +
  facet_wrap(~group_id, ncol = 1, scales = "free_y", labeller = "label_both") +
  theme_bw() +
    theme(strip.text = element_text(size = 10, margin = margin(b = 0, t = 0)))
```