---
title: "Untitled"
author: "Sayani Gupta"
date: "22/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(here)
library(readr)
library(rlang)
library(stringr)
library(purrr)
library(tidyr)
library(dplyr)

  all_files = list.files(path = paste0("../../../data/algo2-600cust/"), 
                         pattern = ".rds")

  names_levels <- map_dfr(all_files, 
                          function(x){
                            z = str_split(str_remove(x, "-nogap.rds"), "-") %>% 
                              unlist()
                            bind_cols(customer_serial_id = z[2]
                                      )
                          })

  
  all_files_path <- paste0("../../../data/algo2-600cust/",
                           all_files)  
  
  
  all_data <- lapply(1:length(all_files_path), function(x){
    
    data = all_files_path %>% magrittr::extract2(x) %>% 
      readRDS()
    
    names = names_levels %>% magrittr::extract(x,)
    
    #names_rep =   names %>% slice(rep(1:n(), each = nrow(data)))
    bind_cols(names, data)
    
  }) %>% bind_rows()
  
  write_rds(all_data, paste0("../../../data/algo2-cust600-wpd-rawdata.rds"))
```

